version: "3.3"
services:
  db:
      image: postgres:latest
      environment:
        POSTGRES_USER: gomouser
        POSTGRES_PASSWORD: gogogomo
        POSTGRES_DB: gomodb

      ports:
        - "5432:5432"